version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: jahresprojekt
    restart: no
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=securepassword123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/postgresql/data

volumes:
  data:
